
version: '3.7'
services:

  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  notification-service-splunk:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "7000:8000"
      - "8088:8088"
    networks:
      notification-net:
        ipv4_address: 172.20.0.5

  #############################################################################################
  ###                                 SPLUNK INIT                                           ###
  #############################################################################################
  splunk-init:
    build:
      context: ./splunk
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PASSWORD}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
    networks:
      - notification-net

  #############################################################################################
  ###                            NTT Data notification service                              ###
  #############################################################################################
  notification-service:
    build:
      context: .
      args:
        - SERVICE_NAME=notification-service
        - MVN_PROFILES=openshift
    ports:
      - "7080:8080"
    environment:
      - spring_profiles_active=${spring_profiles_active}
      - SPLUNK_URL=${SPLUNK_URL}
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      - TOKENS=${TOKENS}
      - UPDATE_CARD_BASE=${UPDATE_CARD_BASE}
    networks:
      notification-net:
        ipv4_address: 172.20.0.6

networks: 
  notification-net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.20.0.0/24
